### ISSUE TITLE
The problem with calculating the decimal number

### ISSUE THREAD

**Issue by evtifiev** [linuxdeepin/deepin-calculator#10]
Any operation with real numbers is interpreted as an operation with a decimal omitting point. Version package 1.0.4.
![calculator_20180721010517](https://user-images.githubusercontent.com/2958882/43027293-32fbad58-8c82-11e8-8073-4e97fb9629d2.png)

**Comment by rekols** [comment]
https://github.com/linuxdeepin/deepin-calculator/commit/2a3cd90e1e82b821799a7391582d49dc1717952d

**Comment by BLumia** [comment]
Should be fixed in https://github.com/linuxdeepin/deepin-calculator/commit/2a3cd90e1e82b821799a7391582d49dc1717952d , closing.
