### ISSUE TITLE
Strange behaviour with equal button

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/deepin-calculator#11]
I get this error when i press `enter` key in an operation:
![deepin-screen-recorder_deepin-calculator_20180803220821](https://user-images.githubusercontent.com/5034215/43661345-8cb040c8-976a-11e8-9b13-3c70586ad96e.gif)
Sometimes also it happens when i click the button with mouse.

Why?
```
OS: Arch Linux
Kernel: x86_64 Linux 4.17.6-1-ARCH
Uptime: 15h 24m
Packages: 1434
Shell: zsh 5.5.1
Resolution: 1920x1080
DE: Deepin 15.6
WM: Deepin WM
WM Theme: Materia-light-compact
GTK Theme: Materia-light-compact [GTK2/3]
Icon Theme: Halo
CPU: Intel Core i7-4720HQ @ 8x 3.6GHz [64.0°C]
GPU: GeForce GTX 960M
RAM: 8452MiB / 15932MiB
```

**Comment by rekols** [comment]
This issue has been fixed and you can view: https://github.com/linuxdeepin/deepin-calculator/commit/2a3cd90e1e82b821799a7391582d49dc1717952d

**Comment by SalahAdDin** [comment]
We have to wait until the new update.

**Comment by SalahAdDin** [comment]
It seems this bug was solved, thanks.
