### ISSUE TITLE
How to use % in it?

### ISSUE THREAD

**Issue by DanyGee** [linuxdeepin/deepin-calculator#12]
How can I calculate for example 5000 - 30%?
When trying 5000-30% it throws an error:
![zrzut ekranu deepin_deepin-calculator_20180911123015](https://user-images.githubusercontent.com/26818551/45354672-7f5cc500-b5be-11e8-9bc4-3529e85bcfcb.png)
![bitmoji](https://render.bitstrips.com/v2/cpanel/e8577c17-750f-45ab-91bc-78d9f838acd0-fe85af63-ad51-4198-8b90-cb1af6ce89fd-v1.png?transparent=1&palette=1&width=246)

**Comment by DanyGee** [comment]
Well, something still isn't right :wink: 
![zrzut ekranu deepin_deepin-calculator_20180913190309](https://user-images.githubusercontent.com/26818551/45503663-c4802300-b787-11e8-8d07-ceec398d8ff6.png)

**Comment by liubailin2017** [comment]
> Well, something still isn't right 
> ![zrzut ekranu deepin_deepin-calculator_20180913190309](https://user-images.githubusercontent.com/26818551/45503663-c4802300-b787-11e8-8d07-ceec398d8ff6.png)

where is mistake?

**Comment by DanyGee** [comment]
How much 30% of 5000 would be?
Definately not 000.3 as this magical calculator says :rofl:

**Comment by avolkov-dazn** [comment]
Wanted to open a bug report since I found deepin-calculator is unable to calculate percentages and seems like there is already one outstanding since 11th of September. This bug renders deeping-calculator unusable in my opinion. Just adding my own screenshot here.

![deepinscreenshot_deepin-calculator_20190210231729](https://user-images.githubusercontent.com/42144053/52541197-2fab4100-2d8a-11e9-856f-6d13a828e5dc.png)

**Comment by cephalopodluke** [comment]
Something like this:

30% = 30/100 = 0.3.

What you want to do is:

5000 - (5000 * 0.3)

**Comment by DanyGee** [comment]
@cephalopodluke I know what I want to do.
The question is: **Does the maintainer now how to properly implement it?**
When I type **5000 - 30%** I expect the result to be **3500** (5000 -1500 = 3500).
![e4f91d37-026a-44d0-91ea-b26cfdaa34a7-7692d7fb-cede-4c34-947c-12129a06b524-v1](https://user-images.githubusercontent.com/26818551/56594877-e5e2a080-65ed-11e9-877f-8295d7ca5ae7.png)

**Comment by cephalopodluke** [comment]
Maybe what you are expecting isn't the correct way of doing math.

**Comment by DanyGee** [comment]
Dozens of other calculators deal with it flawlessly.

**Comment by dylskiMarcin** [comment]
Linked article describes how % operator should behave in calculator.
https://devblogs.microsoft.com/oldnewthing/20080110-00/?p=23853

**Comment by adrienluitot** [comment]
Couldn't be `%` for modulo instead of percentage ? :thinking:

**Comment by dylskiMarcin** [comment]
> Couldn't be `%` for modulo instead of percentage ? :thinking: 

Yeah it would be great, but only when we would considering programmer calculator. So far "deepin-calculator" doesn't even support scientific mode, so...

**Comment by z966768** [comment]
we have do some work,maybe you can try the latest version

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
