### ISSUE TITLE
make 是

### ISSUE THREAD

**Issue by liubailin2017** [linuxdeepin/deepin-calculator#15]
make时报（最后）：

/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdtkwidget.so：对‘qt_version_tag@Qt_5.10’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdtkwidget.so：对‘QPlatformIntegrationFactory::keys(QString const&)@Qt_5_PRIVATE_API’未定义的引用
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libdtkwidget.so：对‘typeinfo for QPlatformDrag@Qt_5_PRIVATE_API’未定义的引用
collect2: error: ld returned 1 exit status
make: *** [Makefile:466：deepin-calculator] 错误 1

deepin 15.8 64位
我看到依赖于 libdtkwidget.so
我电脑上libdtkwidget.so 是指向的一个libdtkwidget.so.2
不知道是不是这个问题？

**Comment by BLumia** [comment]
建议 `sudo apt build-dep deepin-calculator` 或手动装依赖之后再构建。
