### ISSUE TITLE
Deepin calculator missing symbols

### ISSUE THREAD

**Issue by lziron** [linuxdeepin/deepin-calculator#16]
Deepin calculator is not displaying the - and + symbols regardless of what font I use.
![calculator-error](https://user-images.githubusercontent.com/24555644/51998503-f298a200-249f-11e9-952d-6ed0b6b236a9.png)

**Comment by BLumia** [comment]
Should be fixed in https://github.com/linuxdeepin/deepin-calculator/pull/18 (also: https://github.com/linuxdeepin/developer-center/issues/689) . Try update and feel free to let us know if you still have this problem :)
