### ISSUE TITLE
UI Scaling 

### ISSUE THREAD

**Issue by kyr0** [linuxdeepin/deepin-calculator#22]
Hi, 

I'm using deepin 15.10.1 desktop stable and calc 1.0.11-1.

When I set my display scaling to 2 (200%) - the calculator is not scaled accordingly.

![DeepinBildschirmfoto_Bereich auswählen_20190606081213](https://user-images.githubusercontent.com/454817/59010798-cff20d80-8832-11e9-9e7c-3665a6f7bd21.png)

As you can see the display input field scales correctly while the rest of the UI keeps scaling at 100%. Is there anything I can do about it?

Where are the scaling values saved?
Maybe I could just fix the config for an intermediate solution?

Thanks in advance :)

**Comment by z966768** [comment]
thank you for your comment,we have fixed this bug and you can try the latest version
