### ISSUE TITLE
I have finished the scientific mode

### ISSUE THREAD

**Issue by kylemong** [linuxdeepin/deepin-calculator#24]

**Comment by BLumia** [comment]
Seems there is something wrong with [your commit](https://github.com/linuxdeepin/deepin-calculator/pull/23/commits/0ebe8f94528607b38412aff07e73795af43ad5ec). 😅

**Comment by kylemong** [comment]
重新提交了🤓发自我的华为手机-------- 原始邮件 --------主题：Re: [linuxdeepin/deepin-calculator] I have finished the scientific mode (#24)发件人：Gary Wang 收件人：linuxdeepin/deepin-calculator 抄送：kylemong ,Author Seems there is something wrong with your commit. 😅

**Comment by z966768** [comment]
The next version will complete the development of scientific calculators
