### ISSUE TITLE
Symbols for + and - are not being displayed properly

### ISSUE THREAD

**Issue by bhaskar253** [linuxdeepin/deepin-calculator#28]
Symbols for + and - are not being displayed properly
![Issue](https://user-images.githubusercontent.com/9588701/62235394-7ea56b00-b3ea-11e9-9ca1-7d57d20b08cc.png)

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/1417

**Comment by DasJott** [comment]
Same here, but not only - and +
![image](https://user-images.githubusercontent.com/6298761/65313461-af0cb880-db94-11e9-97d2-ada927d13524.png)

**Comment by adrienluitot** [comment]
For me it's also `+`, `-` but also `=`

**Comment by z966768** [comment]
We tested switching system fonts in English mode, and there was no problem.maybe you can try the latest version

**Comment by talesam** [comment]
I have the same problem here! I have the newest version of the calculator v 1.2.2

https://i.imgur.com/EUPKNwn.png

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
