### ISSUE TITLE
Foun an error

### ISSUE THREAD

**Issue by redmanndotsh** [linuxdeepin/deepin-calculator#3]
Hi guys,
@Synk0 found an error on Deepin Calculator. When we put a dot indicating it's about a real number, this is interpreted as a thounsand.

![33906681-6698bb02-df61-11e7-840f-cfe8b219f63f](https://user-images.githubusercontent.com/24627793/33917031-a5f14fac-df8a-11e7-8bea-6fec1a873e6b.jpg)

**Comment by polpoy** [comment]
They are troubles with decimal.
10 x 0.5 = 50

...

**Comment by zwpwjwtz** [comment]
Yes, this problem will only occur if the locale is set to languages (i.e. French) that use point as a separator of digit, instead of a decimal point. This is probably due to the misinterpretation of expressions by the back-end of the calculator.
@rekols An urgent fix is needed for 15.7 🤔

**Comment by zwpwjwtz** [comment]
I believe other issues have the same cause like this one: #5 #10

**Comment by zwpwjwtz** [comment]
Fixed in 2a3cd90 .
