### ISSUE TITLE
Problem calculating

### ISSUE THREAD

**Issue by lucascarpinski** [linuxdeepin/deepin-calculator#31]
Comma and period appear to be interchanged when adding or subtracting

How to solve the problem: Use Gnome Calculator source code

**Comment by z966768** [comment]
We have not distinguished the use of symbols in different regions, and we may add them later

**Comment by z966768** [comment]
This requirement has been collected and may be added in the next cycle

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
