### ISSUE TITLE
Compile Error at Latest commit 6144a21 on 8 Jul 2019.

### ISSUE THREAD

**Issue by softworms** [linuxdeepin/deepin-calculator#33]
deepin-calculator/widgets/iconbutton.h:28: error: unknown type name DWIDGET_USE_NAMESPACE
please fix by replace DWIDGET_USE_NAMESPACE to DGUI_USE_NAMESPACE.

**Comment by BLumia** [comment]
Any other details like your environment, the package version you gonna build, the dtkwidget version you're using and etc?

**Comment by softworms** [comment]
i post environment detail,hope to help you.


os  uos 20 sp1 professional
qt 5.11.3 
qt creator 4.8.2
deepin-calculator last commit version 6144a21b462a51431486417c5471859aad3f7b89


libdtkwidget-bin/unknown 2.2.1-1 amd64
  Deepin graphical user interface library utilities


libdtkwidget-bin-dbgsym/unknown 2.2.1-1 amd64
  debug symbols for libdtkwidget-bin


libdtkwidget-dev/unknown,now 5.1.1-2+rebuild amd64 [installed]
  Deepin graphical user interface library


libdtkwidget2/unknown,now 2.2.1-1 amd64 [installed]
  Deepin graphical user interface library


libdtkwidget2-dbgsym/unknown 2.2.1-1 amd64
  debug symbols for libdtkwidget2


libdtkwidget2-dev/unknown 2.2.1-1 amd64
  Deepin graphical user interface library


libdtkwidget5/unknown,now 5.1.1-2+rebuild amd64 [installed]
  Deepin graphical user interface library


libdtkwidget5-bin/unknown 5.1.1-2+rebuild amd64
  Deepin graphical user interface library utilities


libdtkwidget5-bin-dbgsym/unknown 5.1.1-2+rebuild amd64
  debug symbols for libdtkwidget5-bin


libdtkwidget5-dbgsym/unknown 5.1.1-2+rebuild amd64
  debug symbols for libdtkwidget5



i use apt source
bb@bb-PC:~/Documents/qtwork/deepin-calculator$ sudo apt update
[sudo] password for bb: 
Hit:1 http://uos-packages.deepin.com/uos eagle InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                        
Hit:3 http://dl.google.com/linux/chrome/deb stable Release                                          
Hit:5 https://store.chinauos.com/appstore eagle InRelease







------------------ Original message ------------------
From: "Gary Wang"; 
Sendtime: Thursday, Apr 23, 2020 3:53 PM
To: "linuxdeepin/deepin-calculator"; 
Cc: "彭正帮"<7796816@qq.com>; "Author"; 
Subject: Re: [linuxdeepin/deepin-calculator] Compile Error at Latest commit6144a21 on 8 Jul 2019. (#33)





 
Any other details like your environment, the package version you gonna build, the dtkwidget version you're using and etc?

**Comment by z966768** [comment]
please try latest version

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
