### ISSUE TITLE
Chaining operations fail

### ISSUE THREAD

**Issue by Gargadon** [linuxdeepin/deepin-calculator#4]
Well, I don't know if this needs an explanation. This happens in Arch Linux.
![deepinscreenshot_deepin-calculator_20180323184701](https://user-images.githubusercontent.com/1803846/37858510-0c1aa51e-2ecb-11e8-8c13-abcac3720eea.png)

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/55768686-6d89c480-5ab0-11e9-9687-778b2a2c95da.png)

Should works fine now, try update to the most recent version and check if you still have this issue :)

**Comment by Gargadon** [comment]
Yes, it works fine now.
