### ISSUE TITLE
Operation symbols do not appear when I use the Spanish language

### ISSUE THREAD

**Issue by igatjens** [linuxdeepin/deepin-calculator#42]
The symbols for addition, subtraction, multiplication and division operations are not displayed on the calculator buttons when I use the Spanish language.

If I change the system language to English, the yes displays correctly.

Deepin Calculator version:
apt list deepin-calculator
deepin-calculator/desconocido,now 5.5.21-1 amd64 [instalado]
deepin-calculator/desconocido 5.5.21-1 i386

![Captura de pantalla_área-de-selección_20200922074056](https://user-images.githubusercontent.com/66392244/93890889-0c57b000-fca8-11ea-8fa7-4cbaf1f982e2.png)

**Comment by hugok79** [comment]
Same here.
I use the Portuguese Language.
Deepin 20 (1003)

**Comment by hugok79** [comment]
This have been fix in deepin 20.1 (1010) version

**Comment by hugok79** [comment]
![E5748841-531C-449B-990A-559ADD6EF7E4](https://user-images.githubusercontent.com/16929048/103379981-62c25f00-4adf-11eb-9cba-a9696a8845ef.jpeg)

**Comment by z966768** [comment]
please try the newest version
