### ISSUE TITLE
Add an option for 4-digit separator 增設萬位分隔選項

### ISSUE THREAD

**Issue by heangfat** [linuxdeepin/deepin-calculator#44]
建議為大數提供一个「萬位分隔」的選項，與「千位分隔」並列，以方便中日韓等地的用戶。
分隔字符可用空格，亦可用萬、億、兆、京、垓、秭、壤、溝、澗、正、載這些名稱。如`123456789012345`可顯示為`123 4567 8901 2345`，亦可顯示為`123兆4567億8901萬2345`。
![圖片](https://user-images.githubusercontent.com/20491276/97243264-dff7fc00-1830-11eb-936c-aed6bc0a4a45.png)

[其詳細解釋，可參見此帖。](https://bbs.deepin.org/forum.php?mod=viewthread&tid=149657)

**Comment by z966768** [comment]
谢谢你的建议,已收集
