### ISSUE TITLE
Crash when calculating inverse trigonometric functions

### ISSUE THREAD

**Issue by zwpwjwtz** [linuxdeepin/deepin-calculator#46]
Inputting the following equation and calculating it leads to a crash: 
`arctan(2×sqrt(3))`

Messages from the terminal:
munmap_chunk(): invalid pointer

**Comment by z966768** [comment]
please try the newest version

**Comment by zwpwjwtz** [comment]
It works now. Thanks!

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
