### ISSUE TITLE
Not reliable

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/deepin-calculator#5]
This should be 4.5 instead.

![image](https://user-images.githubusercontent.com/6298761/41024057-6ef1617c-696e-11e8-85ed-2dd5d7ced591.png)

**Comment by scorninpc** [comment]
I have the same problem

![deepin screenshot_selecionar area_20180622180417](https://user-images.githubusercontent.com/2607849/41799290-4c490284-7647-11e8-9c3c-151bd5204525.png)

**Comment by BLumia** [comment]
This seems already fixed. Please update to the most recent version :)
