### ISSUE TITLE
Scientific mode

### ISSUE THREAD

**Issue by VaZark** [linuxdeepin/deepin-calculator#6]
## Complete Scientific mode

There seems to initial setup for scientific mode of the calculator. This task needs to be seen to its end to be a viable option.

What features are currently targeted first for us to contribute?

**Comment by SalahAdDin** [comment]
Yes, and not only that mode, for example, `gnome` calculator have other four:
![modos](https://user-images.githubusercontent.com/5034215/42282575-a9ea7c30-7faf-11e8-9f89-05bfddfb7a76.png)

**Comment by z966768** [comment]
Will be added in the next version
