### ISSUE TITLE
Custom format ou any method to create a simple calc

### ISSUE THREAD

**Issue by scorninpc** [linuxdeepin/deepin-calculator#8]
This calc appear to be a math calc. A simple calc return an exponential result? Or I can change this?

My deepin are PT_br. But format of numbers are different. There's a way to change that?

![deepin screenshot_selecionar area_20180622180417](https://user-images.githubusercontent.com/2607849/41799371-9af98732-7647-11e8-8881-56f576c77fab.png)

**Comment by BLumia** [comment]
Should already be fixed. Feel free to let us know if you still have this issue :)
